spring:
  application:
    name: jakarta_mail_server
  mail:
    host: smtp.gmail.com  # SMTP server host
    port: 465  # SMTP server port (587 for TLS, 465 for SSL)
    username: itugechege@gmail.com  # SMTP username
    password: Admin@Acesoft1  # SMTP password
    protocol: smtp  # SMTP protocol (smtp, smtps)
    properties:
      mail:
        smtp:
          auth: true  # Enable SMTP authentication
          starttls:
            enable: true  # Enable STARTTLS

    # Additional properties for IMAP and POP3
    # Uncomment the sections below as needed

    # imap:
    #   host: imap.example.com  # IMAP server host
    #   port: 993  # IMAP server port (993 for IMAPS)
    #   username: your_username  # IMAP username
    #   password: your_password  # IMAP password
    #   protocol: imap  # IMAP protocol (imap, imaps)
    #   properties:
    #     mail:
    #       imap:
    #         auth: true  # Enable IMAP authentication
    #         starttls:
    #           enable: true  # Enable STARTTLS

    # pop3:
    #   host: pop.example.com  # POP3 server host
    #   port: 995  # POP3 server port (995 for POP3S)
    #   username: your_username  # POP3 username
    #   password: your_password  # POP3 password
    #   protocol: pop3  # POP3 protocol (pop3, pop3s)
    #   properties:
    #     mail:
    #       pop3:
    #         auth: true  # Enable POP3 authentication
    #         starttls:
    #           enable: true  # Enable STARTTLS

